version: '3.7'
services:
  db:
    image: quay.io/minio/minio
    environment:
     - MINIO_ROOT_USER= minio
     - MINIO_ROOT_PASSWORD= minio123
    ports:
     - '9000:9000'
     - '9001:9001'
    volumes:
     - ./data1-1:/data
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data
